version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{queue,debug}]"
