version: '2'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - 9000:9000
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      GF_INSTALL_PLUGINS: "vertamedia-clickhouse-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - clickhouse
  #financial:
  #  image: kmlebedev/clickhouse-exporter-financial:local
  #  environment:
  #    CLICKHOUSE_URL: http://clickhouse:9000
  #  depends_on:
  #    - grafana
  #    - clickhouse
