version: '2'

services:
  server:
    image: kmlebedev/txmlconnector:local
    ports:
      - 3900:3900
    command: "server"
  client:
    image: kmlebedev/txmlconnector:6.19.2.21.8
    command: "client"
    environment:
      TC_LOGIN: "TCNN9979"
      TC_PASSWORD: "n3Z4W4"
      TC_HOST: "tr1-demo5.finam.ru"
      TC_PORT: "3939"
      TC_LOG_LEVEL: "DEBUG"
    depends_on:
      - server
