name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build server
    runs-on: self-hosted

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set BUILD_TIME env
        run: ls

      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date -u +%Y-%m-%d-%H-%M) >> ${GITHUB_ENV}

      - name: Go Release server
        uses: wangyoucao577/go-release-action@feature/asset-name
        with:
          goversion: https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          overwrite: true
          # Where to run `go build .`
          project_path: txmlconnector/server
          binary_name: txmlconnector-server-
          asset_name: "txmlconnector-server-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"